### ISSUE TITLE
data attributes instead of plain srcset, src, sizes attribute

### ISSUE THREAD

**Issue by designcrumble** [imgix/imgix-rails#93] opened 2020-05-17 12:32 UTC
Hi there, 
Is there a way to generate img tags with data attributes as explained in this guide [Imgix with LazySizes](https://blog.imgix.com/2016/05/02/imgix-lazysizes) ?

**Comment by sherwinski** [comment] 2020-05-18 21:08
Hi @designcrumble,

Currently there is no feature for generating `data-src`, `data-srcset`, or `data-sizes`, but we expect to revisit this in the near future when we have more resources to do so. In the meantime, have you considered using the [`loading`](https://caniuse.com/#feat=loading-lazy-attr) attribute?

I'm going to close this issue as it is a duplicate of #60. But feel free to comment back if you have any further questions.

**Closed by sherwinski** 2020-05-18 21:08 UTC

**Comment by designcrumble** [comment] 2020-05-21 04:17
Thanks @sherwinski 
I managed to get the data-src generated but couldn't generate the data-srcset and data-sizes. 
Looking into loading="lazy" as an alternative till then.
