### ISSUE TITLE
ix_picture_tag provides wrong ouput of v3

### ISSUE THREAD

**Issue by Jimmy89** [imgix/imgix-rails#66] opened 2018-10-29 12:46 UTC
Hello all,

I think the output of the ix_picture_tag is not correct. I'm using v3.0.

We have used the following example code:
```
<%= ix_picture_tag('/016a447e-8631-423a-8659-1151ceff973d',
          tag_options: {class: 'media-thumbnail'},
          url_params: {w: 100, h: 100, crop: 'fit'},
          breakpoints: {
    '(max-width: 640px)' => {
      url_params: {
        h: 100,
      },
      tag_options: {
        sizes: 'calc(100vw - 20px)'
      }
    },
    '(max-width: 880px)' => {
      url_params: {
        crop: 'right',
      },
      tag_options: {
        sizes: 'calc(100vw - 20px - 50%)'
      }
    },
    '(min-width: 881px)' => {
      url_params: {
        crop: 'left',
      },
      tag_options: {
        sizes: '430px',
        class: 'media-thumbnail'
      },
    }
  }
```

I expected something it the sense of:
```
<picture>
  <source
   srcset="https://assets.imgix.net/blog/unsplash-kiss.jpg?w=1280"
   media="(min-width: 1280px)"
  >
  <source
    srcset="https://assets.imgix.net/blog/unsplash-kiss.jpg?w=768&h=1024&fit=crop"
    media="(min-width: 768px)"
  >
  <source
    srcset="https://assets.imgix.net/blog/unsplash-kiss.jpg?w=568&h=320&fit=crop"
    media="(min-width: 480px)"
  >
  <img src="https://assets.imgix.net/blog/unsplash-kiss.jpg?w=320&h=568&fit=crop">
</picture>
```

I copied this output of the example page, so It does not correspond with the actual expected output. The point is, I get _this_ LONG list of html as ouput:
```
<picture class="media-thumbnail"><source sizes="calc(100vw - 20px)" media="(max-width: 640px)" srcset="https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=100&amp;h=100&amp;crop=fit 100w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=116&amp;h=116&amp;crop=fit 116w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=134&amp;h=134&amp;crop=fit 134w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=156&amp;h=156&amp;crop=fit 156w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=182&amp;h=182&amp;crop=fit 182w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=210&amp;h=210&amp;crop=fit 210w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=244&amp;h=244&amp;crop=fit 244w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=282&amp;h=282&amp;crop=fit 282w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=328&amp;h=328&amp;crop=fit 328w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=380&amp;h=380&amp;crop=fit 380w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=442&amp;h=442&amp;crop=fit 442w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=512&amp;h=512&amp;crop=fit 512w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=594&amp;h=594&amp;crop=fit 594w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=688&amp;h=688&amp;crop=fit 688w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=798&amp;h=798&amp;crop=fit 798w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=926&amp;h=926&amp;crop=fit 926w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=1074&amp;h=1074&amp;crop=fit 1074w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=1246&amp;h=1246&amp;crop=fit 1246w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=1446&amp;h=1446&amp;crop=fit 1446w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=1678&amp;h=1678&amp;crop=fit 1678w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=1946&amp;h=1946&amp;crop=fit 1946w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=2258&amp;h=2258&amp;crop=fit 2258w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=2618&amp;h=2618&amp;crop=fit 2618w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=3038&amp;h=3038&amp;crop=fit 3038w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=3524&amp;h=3524&amp;crop=fit 3524w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=4088&amp;h=4088&amp;crop=fit 4088w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=4742&amp;h=4742&amp;crop=fit 4742w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=5500&amp;h=5500&amp;crop=fit 5500w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=6380&amp;h=6380&amp;crop=fit 6380w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=7400&amp;h=7400&amp;crop=fit 7400w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;crop=fit"></source><source sizes="calc(100vw - 20px - 50%)" media="(max-width: 880px)" srcset="https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=100&amp;h=100&amp;crop=right 100w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=116&amp;h=116&amp;crop=right 116w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=134&amp;h=134&amp;crop=right 134w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=156&amp;h=156&amp;crop=right 156w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=182&amp;h=182&amp;crop=right 182w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=210&amp;h=210&amp;crop=right 210w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=244&amp;h=244&amp;crop=right 244w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=282&amp;h=282&amp;crop=right 282w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=328&amp;h=328&amp;crop=right 328w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=380&amp;h=380&amp;crop=right 380w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=442&amp;h=442&amp;crop=right 442w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=512&amp;h=512&amp;crop=right 512w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=594&amp;h=594&amp;crop=right 594w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=688&amp;h=688&amp;crop=right 688w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=798&amp;h=798&amp;crop=right 798w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=926&amp;h=926&amp;crop=right 926w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=1074&amp;h=1074&amp;crop=right 1074w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=1246&amp;h=1246&amp;crop=right 1246w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=1446&amp;h=1446&amp;crop=right 1446w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=1678&amp;h=1678&amp;crop=right 1678w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=1946&amp;h=1946&amp;crop=right 1946w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=2258&amp;h=2258&amp;crop=right 2258w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=2618&amp;h=2618&amp;crop=right 2618w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=3038&amp;h=3038&amp;crop=right 3038w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=3524&amp;h=3524&amp;crop=right 3524w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=4088&amp;h=4088&amp;crop=right 4088w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=4742&amp;h=4742&amp;crop=right 4742w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=5500&amp;h=5500&amp;crop=right 5500w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=6380&amp;h=6380&amp;crop=right 6380w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=7400&amp;h=7400&amp;crop=right 7400w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;crop=right"></source><source sizes="430px" class="media-thumbnail" media="(min-width: 881px)" srcset="https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=100&amp;h=100&amp;crop=left 100w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=116&amp;h=116&amp;crop=left 116w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=134&amp;h=134&amp;crop=left 134w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=156&amp;h=156&amp;crop=left 156w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=182&amp;h=182&amp;crop=left 182w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=210&amp;h=210&amp;crop=left 210w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=244&amp;h=244&amp;crop=left 244w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=282&amp;h=282&amp;crop=left 282w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=328&amp;h=328&amp;crop=left 328w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=380&amp;h=380&amp;crop=left 380w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=442&amp;h=442&amp;crop=left 442w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=512&amp;h=512&amp;crop=left 512w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=594&amp;h=594&amp;crop=left 594w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=688&amp;h=688&amp;crop=left 688w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=798&amp;h=798&amp;crop=left 798w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=926&amp;h=926&amp;crop=left 926w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=1074&amp;h=1074&amp;crop=left 1074w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=1246&amp;h=1246&amp;crop=left 1246w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=1446&amp;h=1446&amp;crop=left 1446w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=1678&amp;h=1678&amp;crop=left 1678w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=1946&amp;h=1946&amp;crop=left 1946w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=2258&amp;h=2258&amp;crop=left 2258w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=2618&amp;h=2618&amp;crop=left 2618w, https://CLIENT.imgix.net/016a447e-8631-423a-8659-1151ceff973d?ixlib=rails-3.0.0&amp;w=3038&amp;h=3038&amp;crop=left 3038w, https://CLIENT.imgix.net/016a44...
```
etc..

Each srcset _including_ the `<img>` tag gets a huge output with all kinds of dimensions, not even corresponding the the srcset value. This cannot be right..

**Comment by jayeb** [comment] 2018-10-29 19:35
Hi @Jimmy89, thanks for the ticket.

After looking through the information you provided, I'm pleased (or displeased, from a certain perspective) to inform you that what you're seeing is the intended behavior of this library as of version 3.0. The output you included from our example page is out of date, it seems--that's on me. There was a bit of confusion surrounding the recent 3.0 release and apparently the examples were yet another thing I let slip through the cracks. I'll prioritize fixing those very soon.

In order to explain what's going on here, I'm going to take a step back and look at how the `srcset` and `sizes` attributes work, and how this meshes with the goals of this library. If you already know and understand this stuff feel free to skip over the next paragraph, but I'm going to put it in anyway for the sake of any less-experienced developers that may stumble across this ticket in the future.

When using `<picture>` and `<source>` to display responsive images, the browser decides which `<source>` element to use based on its media query, then selects which image URL to fetch from the `<source>` element's `srcset` list based on that `<source>` element's `sizes` attribute (which can be an absolute pixel value, or a relative value). While we'd love to be able to examine things as the browser does and provide a single perfect imgix URL for the given circumstances,  unfortunately for us the information available at the time `imgix-rail` is doing its thing is tragically incomplete. So what we can do instead is provide a robust set URLs in the `srcset` list (by varying the rendered width via the `w` parameter) that the browser can choose a near-perfect image to display no matter what its selection mechanism settles on as its ideal width, height, and pixel density.

While I agree that on their face, the robust `srcset` lists we're providing may seem absurdly long, we feel quite strongly that this is the correct approach. As stated above, a robust `srcset` list allows your users' browsers to select the best possible image to fill any sized container at any screen resolution. Our default algorithm ensures that no matter the circumstances, the browser will always be able to choose an image that is within 8% of its rendered dimensions, which guarantees high visual fidelity for your end users and cuts down on wasted bandwidth. It may seem excessivley long, but the robust `srcset` can pay huge dividends for your users.

The *cost* of this robust `srcset`, on the other hand, is next to zero:

- It costs you nothing to generate: just call the helper function
- The additional HTML bytes shipped to your users are largely negligible compared to the bytes you save by ensuring they download a properly-sized image
- We've seen no negative performance implications for browsers parsing large `srcset` attributes

Are there things we can do to improve this code? Certainly. We could do a better job of examining the `sizes` value provided for each `<source>` element, and if we determine that the value provided represents an absolute pixel dimension (as your last breakpoint does) we could provide a more focused `srcset` that lists specific image dimensions at `2x`, `3x`, etc instead of our standard width array. We fully intend to improve this algorithm further over time, but this specific behavior isn't on the roadmap at the moment. If you or any of our community members following along would like to tackle this sooner, though, PRs are always welcome!

If you find yourself unconvinced, though, you can still pass your own `widths` list as an option when you call the `ix_picture_tag` helper to override the automatically-generated `srcset` list. However, in typing up this response I noticed a bug in that code (the `widths` argument [doesn't seem to be passed through](https://github.com/imgix/imgix-rails/blob/master/lib/imgix/rails/view_helper.rb#L15-L17))--look for version 3.0.1 to come out shortly to address this.

Since there's no fix to be made here directly, I'm going to close this ticket, but I'm happy to continue discussing if you have further questions or concerns.

**Closed by jayeb** 2018-10-29 19:35 UTC
